---
- name: Update repository Oracle Linux
  hosts: myhost
  become: true

  tasks:
    - name: upgrade all pakcages
      yum:
        name: '*'
        state: latest
    
    - name: install mysql server
      yum:
        name: mysql-server
        state: latest

    - name: enable service mysqld
      service:
        name: mysqld.service
        enabled: yes
    
    - name: start service mysqld
      service:
        name: mysqld.service
        state: started