---
- name: Update repository Oracle Linux
  hosts: myhost
  become: true

  tasks:
    - name: upgrade all pakcages
      yum:
        name: '*'
        state: latest
    
    - name: install mysql server
      yum:
        name: mysql-server
        state: latest